<h1><center>SVM Classification Tree</center></h1>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../data/Movie_classification.csv')

In [3]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [4]:
df.tail()

Marketing expense  Production expense  Multiplex coverage     Budget  \
501            21.2526               78.86               0.427  36624.115   
502            20.9054               78.86               0.427  33996.600   
503            21.2152               78.86               0.427  38751.680   
504            22.1918               78.86               0.427  37740.670   
505            20.9482               78.86               0.427  33496.650   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
501         142.6                8.68                8.775            8.620   
502         150.2                8.78                8.945            8.770   
503         164.5                8.83                8.970            8.855   
504         162.8                8.73                8.845            8.800   
505         154.3                8.64                8.880            8.680   

     Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
501            8.970            6.8         492480           NO      186.96   
502            8.930            7.8         482875          YES      132.24   
503            9.010            7.8         532239           NO      109.56   
504            8.845            6.8         496077          YES      158.80   
505            8.790            6.8         518438          YES      205.60   

     Twitter_hastags   Genre  Avg_age_actors  Num_multiplex  Collection  \
501          243.584  Action              27            561       44800   
502          263.296  Action              20            600       41200   
503          243.824  Comedy              31            576       47800   
504          303.520  Comedy              47            607       44000   
505          203.040  Comedy              45            604       38000   

     Start_Tech_Oscar  
501                 0  
502                 0  
503                 0  
504                 0  
505                 0

In [5]:
df.shape

(506, 19)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
Marketing expense      506 non-null float64
Production expense     506 non-null float64
Multiplex coverage     506 non-null float64
Budget                 506 non-null float64
Movie_length           506 non-null float64
Lead_ Actor_Rating     506 non-null float64
Lead_Actress_rating    506 non-null float64
Director_rating        506 non-null float64
Producer_rating        506 non-null float64
Critic_rating          506 non-null float64
Trailer_views          506 non-null int64
3D_available           506 non-null object
Time_taken             494 non-null float64
Twitter_hastags        506 non-null float64
Genre                  506 non-null object
Avg_age_actors         506 non-null int64
Num_multiplex          506 non-null int64
Collection             506 non-null int64
Start_Tech_Oscar       506 non-null int64
dtypes: float64(12), int64(5), object(2)
memory usage: 75.2+ KB


In [7]:
df.isnull().sum()

Marketing expense       0
Production expense      0
Multiplex coverage      0
Budget                  0
Movie_length            0
Lead_ Actor_Rating      0
Lead_Actress_rating     0
Director_rating         0
Producer_rating         0
Critic_rating           0
Trailer_views           0
3D_available            0
Time_taken             12
Twitter_hastags         0
Genre                   0
Avg_age_actors          0
Num_multiplex           0
Collection              0
Start_Tech_Oscar        0
dtype: int64

In [8]:
df['Time_taken'].fillna(value=df['Time_taken'].mean(), inplace=True)

In [9]:
df = pd.get_dummies(df, columns = ['3D_available', 'Genre'], drop_first=True)

In [10]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Time_taken  Twitter_hastags  \
0            7.995           7.94  ...      109.60          223.840   
1            7.470           7.44  ...      146.64          243.456   
2            7.515           7.44  ...      147.88         2022.400   
3            7.020           8.26  ...      185.36          225.344   
4            7.070           8.26  ...      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  Start_Tech_Oscar  \
0              23            494       48000                 1   
1              42            462       43200                 0   
2              38            458       69400                 1   
3              45            472       66800                 1   
4              55            395       72400                 1   

   3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
0                 1             0            0               1  
1                 0             0            1               0  
2                 0             1            0               0  
3                 1             0            1               0  
4                 0             0            1               0  

[5 rows x 21 columns]

In [11]:
X = df.loc[:, df.columns!='Start_Tech_Oscar'].values
y = df['Start_Tech_Oscar'].values

#### Train test split

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.2)

#### Standardizing the data

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
X_train_std = StandardScaler().fit_transform(X_train)

In [16]:
X_test_std = StandardScaler().fit(X_train).transform(X_test)

#### Training Classification Tree

In [17]:
from sklearn.svm import SVC

In [18]:
clf_svm_l =  SVC(C=0.01, kernel='linear')
clf_svm_l.fit(X_train_std, y_train)

SVC(C=0.01, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [19]:
y_test_pred = clf_svm_l.predict(X_test_std)
y_train_pred = clf_svm_l.predict(X_train_std)

#### Model Performance

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [21]:
accuracy_score(y_test, y_test_pred)

0.6274509803921569

In [22]:
confusion_matrix(y_test, y_test_pred)

array([[11, 33],
       [ 5, 53]], dtype=int64)

In [23]:
accuracy_score(y_train, y_train_pred)

0.6064356435643564

In [24]:
clf_svm_l.n_support_

array([186, 189])

#### Grid Search

In [25]:
from sklearn.model_selection import GridSearchCV

In [26]:
params = {'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50, 100, 1000)}

In [27]:
clf_svm_l = SVC(kernel='linear')

In [28]:
svm_grid_lin = GridSearchCV(clf_svm_l, params, n_jobs=1, cv=10, verbose=1, scoring='accuracy')

In [29]:
svm_grid_lin.fit(X_train_std, y_train)

Fitting 10 folds for each of 12 candidates, totalling 120 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 120 out of 120 | elapsed:   59.4s finished


GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=1,
             param_grid={'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50,
                               100, 1000)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=1)

In [30]:
svm_grid_lin.best_params_

{'C': 0.1}

In [31]:
linsvm_clf = svm_grid_lin.best_estimator_

In [32]:
accuracy_score(y_test, linsvm_clf.predict(X_test_std))

0.5980392156862745

In [33]:
linsvm_clf

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

#### Polynomial

In [34]:
clf_svm_p3 = SVC(kernel='poly', degree=2, C=0.1)
clf_svm_p3.fit(X_train_std, y_train)

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=2, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [35]:
y_train_pred = clf_svm_p3.predict(X_train_std)
y_test_pred = clf_svm_p3.predict(X_test_std)

In [36]:
accuracy_score(y_test, y_test_pred)

0.5588235294117647

In [37]:
confusion_matrix(y_test, y_test_pred)

array([[ 0, 44],
       [ 1, 57]], dtype=int64)

In [38]:
clf_svm_p3.n_support_

array([185, 194])

#### Radial

In [39]:
clf_svm_r = SVC(kernel='rbf', gamma=0.5, C=10)
clf_svm_r.fit(X_train_std, y_train)

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [40]:
y_test_pred = clf_svm_r.predict(X_test_std)
y_train_pred = clf_svm_r.predict(X_train_std)

In [41]:
accuracy_score(y_test, y_test_pred)

0.6176470588235294

In [42]:
confusion_matrix(y_test, y_test_pred)

array([[16, 28],
       [11, 47]], dtype=int64)

In [43]:
clf_svm_r.n_support_

array([186, 218])

#### Radial Grid

In [44]:
params = {'C': (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50), 'gamma': (0.001, 0.01, 0.1, 0.5, 1)}

In [45]:
clf_svm_r = SVC(kernel='rbf')

In [46]:
svm_grid_rad = GridSearchCV(clf_svm_r, params, n_jobs=-1, cv=3, verbose=1, scoring='accuracy')

In [47]:
svm_grid_rad.fit(X_train_std, y_train)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.


Fitting 3 folds for each of 40 candidates, totalling 120 fits


[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:    0.7s
[Parallel(n_jobs=-1)]: Done  97 out of 120 | elapsed:    0.8s remaining:    0.1s
[Parallel(n_jobs=-1)]: Done 120 out of 120 | elapsed:    0.9s finished


GridSearchCV(cv=3, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50),
                         'gamma': (0.001, 0.01, 0.1, 0.5, 1)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=1)

In [48]:
svm_grid_rad.best_params_

{'C': 50, 'gamma': 0.001}

In [49]:
radsvm_clf = svm_grid_rad.best_estimator_

In [50]:
accuracy_score(y_test, radsvm_clf.predict(X_test_std))

0.6176470588235294

<h1><center>The End</center></h1>
<p><center>By <b>Alvyn Abranches</b></center></p>